# CartPole

In [20]:
import gymnasium as gym
from IPython.core.display_functions import display

In [34]:
e = gym.make("CartPole-v1")
obs, info = e.reset()

display(obs)
display(info)

array([-0.04458623,  0.00293646,  0.01232894,  0.01563742], dtype=float32)

{}

In [35]:
display(e.action_space)
display(e.observation_space)

Discrete(2)

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)

In [39]:
display(e.action_space.sample())
display(e.observation_space.sample())

np.int64(0)

array([3.3338876 , 0.5420005 , 0.31491232, 0.11180086], dtype=float32)

In [40]:
e.step(0)

(array([-0.0445275 , -0.19236012,  0.01264169,  0.31218463], dtype=float32),
 1.0,
 False,
 False,
 {})

In [45]:
env = gym.make("CartPole-v1")
total_reward = 0.0
total_steps = 0
obs, _ = env.reset()

while True:
    action = e.action_space.sample()
    obs, reward, is_done, is_trunc, _ = env.step(action)

    total_reward += reward
    total_steps += 1

    if is_done:
        break

print(f"Episode finished in {total_steps} steps, total reward {total_reward:.2f}")

Episode finished in 11 steps, total reward 11.00
