# CartPole

In [2]:
import gymnasium as gym
from IPython.core.display_functions import display

In [3]:
e = gym.make("CartPole-v1")
obs, info = e.reset()

display(obs)
display(info)

array([ 0.03171167,  0.04135437, -0.01878487,  0.02530249], dtype=float32)

{}

In [4]:
display(e.action_space)
display(e.observation_space)

Discrete(2)

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)

In [5]:
display(e.action_space.sample())
display(e.observation_space.sample())

np.int64(0)

array([ 0.99617964,  0.05524895, -0.3138159 , -0.6642519 ], dtype=float32)

In [6]:
e.step(0)

(array([ 0.03253876, -0.15349323, -0.01827882,  0.3119999 ], dtype=float32),
 1.0,
 False,
 False,
 {})

-----

In [9]:
env = gym.make("CartPole-v1")
total_reward = 0.0
total_steps = 0
obs, _ = env.reset()

while True:
    action = env.action_space.sample()
    obs, reward, is_done, is_trunc, _ = env.step(action)

    total_reward += reward
    total_steps += 1

    if is_done:
        break

print(f"Episode finished in {total_steps} steps, total reward {total_reward:.2f}")

Episode finished in 19 steps, total reward 19.00


------

In [10]:
import gymnasium as gym
import random

In [11]:
class RandomActionWrapper(gym.ActionWrapper):
    def __init__(self, env: gym.Env, epsilon: float = 1.0):
        super(RandomActionWrapper, self).__init__(env)
        self.epsilon = epsilon

    def action(self, action: gym.core.WrapperActType) -> gym.core.WrapperActType:
        if random.random() < self.epsilon:
            action = self.env.action_space.sample()
            print(f"Random action: {action}")
            return action

        return action


In [12]:
env = RandomActionWrapper(gym.make("CartPole-v1"))
obs = env.reset()
total_reward = 0.0
total_steps = 0

while True:
    obs, reward, is_done, _, _ = env.step(0)
    total_reward += reward
    total_steps += 1
    if is_done:
        break

print(f"Episode finished in {total_steps} steps, total reward {total_reward:.2f}")

Random action: 1
Random action: 1
Random action: 0
Random action: 1
Random action: 1
Random action: 0
Random action: 0
Random action: 0
Random action: 0
Random action: 1
Random action: 0
Random action: 0
Random action: 0
Random action: 1
Random action: 1
Random action: 0
Random action: 0
Random action: 1
Random action: 0
Random action: 0
Random action: 0
Random action: 0
Random action: 0
Random action: 0
Random action: 1
Random action: 0
Random action: 0
Random action: 1
Episode finished in 28 steps, total reward 28.00


-----

In [3]:
import gymnasium as gym
import random

In [4]:
env = gym.make("CartPole-v1", render_mode='rgb_array')
env = gym.wrappers.RecordVideo(env, video_folder="./video")
env = gym.wrappers.HumanRendering(env)

/home/ezio4df/projects/LearningRes/Bk-DeepRLHandsOn-MaximLapan/.venv/lib/python3.13/site-packages/gymnasium/wrappers/rendering.py:293: UserWarning: WARN: Overwriting existing videos at /home/ezio4df/projects/LearningRes/Bk-DeepRLHandsOn-MaximLapan/video folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


In [7]:
env = gym.make("CartPole-v1")
total_reward = 0.0
total_steps = 0
obs, _ = env.reset()

while True:
    action = env.action_space.sample()
    obs, reward, is_done, is_trunc, _ = env.step(action)

    total_reward += reward
    total_steps += 1

    if is_done:
        break

print(f"Episode finished in {total_steps} steps, total reward {total_reward:.2f}")

Episode finished in 15 steps, total reward 15.00


In [8]:
env.close()